# Generated by Django 6.0.3 on 2026-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assistance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assistance_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
