# Generated by Django 6.0.3 on 2026-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverstatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('IN_PROGRESS', 'On Trip')], default='AVAILABLE', max_length=20),
        ),
    ]
