# Generated by Django 6.0.3 on 2026-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_driverstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverstatus',
            name='qualification',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='driverstatus',
            name='specialization',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
